<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>

<div class="catalog-product-view-tab-make-your-style">
    <div class="actions dropdown make-your-style-dropdown">
        <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
            <span><?= __('Select option'); ?></span>
        </span>
        <ul class="dropdown">
            <li>
                <span class="item">One</span>
            </li>
            <li>
                <span class="item">Two</span>
            </li>
            <li>
                <span class="item">Three</span>
            </li>
        </ul>
    </div>
</div>
