<div class="registartion-for-dealer">
    <a href="javascript:;"
       id="register-dealer"
       data-mage-init='{"dealerPopup": {"config":""}}'>
        <?= $block->escapeHtml(__('Registration for dealer')); ?>
    </a>
</div>

<div id="register-dealer-modal">
</div>

<!--<script type="text/x-magento-init">-->
<!--   {-->
<!--        "#register-dealer": {-->
<!--            "dealerPopup": {-->
<!--            }-->
<!--        }-->
<!--   }-->
<!--</script>-->
