<div class="showperson">
    <h2><?= __('Personal info') ?>:</h2>
    <?php if ($block->getName()): ?>
    <p><?= __('Name') ?> - <?= $block->getName(); ?></p>
    <?php endif; ?>

    <?php if ($block->getLastname()): ?>
    <p><?= __('Last Name') ?> - <?= $block->getLastname(); ?></p>
    <?php endif; ?>

    <?php if ($block->getLinkToJson()) : ?>
    <a href="<?= $block->getLinkToJson(); ?>"><?= __('Link to JSON controller') ?></a>
    <?php endif; ?>
</div>
